apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-ss8y
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-ss8y
    app.kubernetes.io/part-of: my-app
  name: devfile-sample-ss8y
spec:
  rules:
  - host: devfile-sample-ss8y-rh-ee-sombaner-tenant.api-y00zljez-centralindia-aroapp-io:6443
    http:
      paths:
      - backend:
          service:
            name: devfile-sample-ss8y
            port:
              number: 3001
        path: /
        pathType: ImplementationSpecific
status:
  loadBalancer: {}
